apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: multi-step-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: step1
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "Hello, Argo Workflows!"
    - - name: step2
        template: list-files

  - name: print-message
    inputs:
      parameters:
      - name: message
    container:
      image: busybox
      command: [sh, -c]
      args: ["echo {{inputs.parameters.message}}"]

  - name: list-files
    container:
      image: busybox
      command: [sh, -c]
      args: ["ls /"]
