apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: multi-step-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: step1
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "Hello Argo"
      - name: step2
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "This is step 2"
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
