apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parallel-example-
spec:
  entrypoint: parallel
  templates:
  - name: parallel
    steps:
    - - name: step1
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "Task 1"
      - name: step2
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "Task 2"
      - name: step3
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "Task 3"
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
