apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parallel-busybox-
spec:
  entrypoint: parallel-steps
  templates:
    - name: parallel-steps
      steps:
        - - name: step-1
            template: busybox-task
            arguments:
              parameters:
                - name: message
                  value: "Hello from step 1"
        - - name: step-2
            template: busybox-task
            arguments:
              parameters:
                - name: message
                  value: "Hello from step 2"

    - name: busybox-task
      inputs:
        parameters:
          - name: message
      container:
        image: busybox
        command: [ "sh", "-c" ]
        args: [ "echo {{inputs.parameters.message}}" ]
